## About
This is to understand the datasets so I can develop an intution to the
problem solved.

In [1]:
import os
import pandas as pd

In [2]:
DATASET = os.path.join("..","..","dataset")

## Competition data

In [6]:
train_df = pd.read_csv(os.path.join(DATASET, "competitions","eedi-mining-misconceptions-in-mathematics","train.csv"))
## COnvert column MisconceptionAId from float to string
train_df['MisconceptionAId'] = train_df['MisconceptionAId'].astype(str)
train_df['MisconceptionBId'] = train_df['MisconceptionBId'].astype(str)
train_df['MisconceptionCId'] = train_df['MisconceptionCId'].astype(str)
train_df['MisconceptionDId'] = train_df['MisconceptionDId'].astype(str)
train_df.head()

,QuestionId,ConstructId,ConstructName,SubjectId,SubjectName,CorrectAnswer,QuestionText,AnswerAText,AnswerBText,AnswerCText,AnswerDText,MisconceptionAId,MisconceptionBId,MisconceptionCId,MisconceptionDId
0,0,856,Use the order of operations to carry out calcu...,33,BIDMAS,A,\[\n3 \times 2+4-5\n\]\nWhere do the brackets ...,\( 3 \times(2+4)-5 \),\( 3 \times 2+(4-5) \),\( 3 \times(2+4-5) \),Does not need brackets,nan,nan,nan,1672.0
1,1,1612,Simplify an algebraic fraction by factorising ...,1077,Simplifying Algebraic Fractions,D,"Simplify the following, if possible: \( \frac{...",\( m+1 \),\( m+2 \),\( m-1 \),Does not simplify,2142.0,143.0,2142.0,nan
2,2,2774,Calculate the range from a list of data,339,Range and Interquartile Range from a List of Data,B,Tom and Katie are discussing the \( 5 \) plant...,Only\nTom,Only\nKatie,Both Tom and Katie,Neither is correct,1287.0,nan,1287.0,1073.0
3,3,2377,Recall and use the intersecting diagonals prop...,88,Properties of Quadrilaterals,C,The angles highlighted on this rectangle with ...,acute,obtuse,\( 90^{\circ} \),Not enough information,1180.0,1180.0,nan,1180.0
4,4,3387,Substitute positive integer values into formul...,67,Substitution into Formula,A,The equation \( f=3 r^{2}+3 \) is used to find...,\( 30 \),\( 27 \),\( 51 \),\( 24 \),nan,nan,nan,1818.0

In [7]:
## print the number of unique QuestionId, SubjectId, SubjectName
print("Unique QuestionId:", train_df['QuestionId'].nunique())
print("Unique SubjectId:", train_df['SubjectId'].nunique())
print("Unique SubjectName:", train_df['SubjectName'].nunique())
## Print the number of unique MisconceptionAId, MisconceptionBId, MisconceptionCId, MisconceptionDId. here we have to combine all the misconceptions into one and get the unique values
misconceptions = pd.concat([train_df['MisconceptionAId'], train_df['MisconceptionBId'], 
                            train_df['MisconceptionCId'], train_df['MisconceptionDId']])
print("Unique MisconceptionId:", misconceptions.nunique())

Unique QuestionId: 1869
Unique SubjectId: 163
Unique SubjectName: 163
Unique MisconceptionId: 1605

## Other generated data analysis

In [ ]:
folders = os.listdir(os.path.join(DATASET, "datasets","conjuring92"))

train_df = pd.read_csv(os.path.join(DATASET, "competitions","eedi-mining-misconceptions-in-mathematics","train.csv"))

In [4]:
cot_train_parquet = pd.read_parquet(os.path.join(DATASET, "datasets","conjuring92","eedi-ranker-silver-v3-teacher-blended-cot","versions","9","train.parquet"))
cot_train_parquet.head()

,query_id,content_id,SubjectName,ConstructName,QuestionText,CorrectAnswerText,InCorrectAnswerText,MisconceptionName,AllOptionText,label,teacher_score,cot
0,1_A,2142,Simplifying Algebraic Fractions,Simplify an algebraic fraction by factorising ...,"Simplify the following, if possible: \( \frac{...",Does not simplify,\( m+1 \),Does not know that to factorise a quadratic ex...,\n- \( m+1 \)\n- \( m+2 \)\n- \( m-1 \)\n- Doe...,1,3.06250,The student incorrectly assumed that when divi...
1,1_A,2398,Simplifying Algebraic Fractions,Simplify an algebraic fraction by factorising ...,"Simplify the following, if possible: \( \frac{...",Does not simplify,\( m+1 \),Thinks you can divide terms by different facto...,\n- \( m+1 \)\n- \( m+2 \)\n- \( m-1 \)\n- Doe...,0,2.96875,The student incorrectly assumed that when divi...
2,1_A,2581,Simplifying Algebraic Fractions,Simplify an algebraic fraction by factorising ...,"Simplify the following, if possible: \( \frac{...",Does not simplify,\( m+1 \),When factorising a quadratic with a coefficien...,\n- \( m+1 \)\n- \( m+2 \)\n- \( m-1 \)\n- Doe...,0,1.87500,The student incorrectly assumed that when divi...
3,1_A,2068,Simplifying Algebraic Fractions,Simplify an algebraic fraction by factorising ...,"Simplify the following, if possible: \( \frac{...",Does not simplify,\( m+1 \),Does not know that to factorise a quadratic ex...,\n- \( m+1 \)\n- \( m+2 \)\n- \( m-1 \)\n- Doe...,0,2.93750,The student incorrectly assumed that when divi...
4,1_A,838,Simplifying Algebraic Fractions,Simplify an algebraic fraction by factorising ...,"Simplify the following, if possible: \( \frac{...",Does not simplify,\( m+1 \),When factorising a quadratic without a non var...,\n- \( m+1 \)\n- \( m+2 \)\n- \( m-1 \)\n- Doe...,0,-0.09375,The student incorrectly assumed that when divi...